export enum Errors {
  UNEXPECTED_TYPE_FOR_PARAMETER = 'UNEXPECTED_TYPE_FOR_PARAMETER',
  UNEXPECTED_TYPE_FOR_EXPRESSION = 'UNEXPECTED_TYPE_FOR_EXPRESSION',
  UNEXPECTED_LAMBDA = 'UNEXPECTED_LAMBDA',
  NOT_A_FUNCTION = 'NOT_A_FUNCTION',
  UNDEFINED_VARIABLE = 'UNDEFINED_VARIABLE',
  MISSING_MAIN = 'MISSING_MAIN',
  INCORRECT_NUMBER_OF_ARGUMENTS = 'INCORRECT_NUMBER_OF_ARGUMENTS',
  ILLEGAL_NEGATIVE_LITERAL = 'ILLEGAL_NEGATIVE_LITERAL',

  MAIN_ALREADY_EXISTS = 'MAIN_ALREADY_EXISTS',
}
